EPMEDU-2314: The About Page – Minor Spelling Issues
AnimealProject/animeal_iOS pull request #195
Opened 2023-08-23 13:28 UTC by vadimotion

## What's new:
The [EPMEDU-2314: Text on the page has several minor spelling issues](https://jira.epam.com/jira/browse/EPMEDU-2314) is fixed:
- Minor spelling issues are fixed on the `About Page`
- `Strings.swift` file generated by the `SwiftGen` tool is included in `.gitignore` file

## Before:
<img width="474" alt="Screenshot 2023-08-23 at 16 23 15" src="https://github.com/AnimealProject/animeal_iOS/assets/36302791/ab767572-bbf7-41d6-93dc-149685f5b7c0">

## After:
<img width="474" alt="Screenshot 2023-08-23 at 16 18 05" src="https://github.com/AnimealProject/animeal_iOS/assets/36302791/af2b6795-64a1-4b7f-886c-286484bfdc76">

2023-08-23 15:21 UTC, kishorepran commented on animeal/src/Common/Strings.swift
Removing unused code is awesome.
Initial look says it might have dependencies at multiple places.
Just to double check if this is and intended change. 
Rest all good.

2023-08-28 12:03 UTC, rinold commented on animeal/src/Common/Strings.swift
Strings.swift is generated file (using SwiftGen) that contains localization enum based on Localizable.strings file. We should not remove it from repo.

2023-08-28 12:04 UTC, rinold requested changes
Please revert the removal of Strings.swift. Also note that this file is added to the .Xcode proj, and removing just the source of it on disk will lead to corrupted file reference in project.

2023-08-28 17:49 UTC, kishorepran commented on animeal/src/Common/Strings.swift
@vadimotion  :If possible kindly pull from dev as well. It will help pass the CI/CD checks here.

2023-09-07 09:09 UTC, kishorepran approved these changes

2023-09-07 09:09 UTC, kishorepran commented on animeal/src/Common/Strings.swift
Thanks @vadimotion: for the update.
@rinold : I have checked that the stings file is reverted. Then entry from gitignore is removed. Kindly review.
Good to go from my side.

2023-09-13 13:36 UTC, rinold approved these changes

2023-09-13 13:37 UTC, merged